# Dockerfile
FROM tomee:8-jre-1.7.5-plus

COPY jaxrs-1.0-SNAPSHOT.war /usr/local/tomee/webapps/jaxrs-1.0-SNAPSHOT.war
# COPY <locationofapplication>/<warfile> /usr/local/tomee/webapps/<warfile>
# sudo docker build -t ukrsite/jaxrs:1 .
# docker run -d -p 27017-27019:27017-27019 --name mongodb mongo:latest
